#!/usr/bin/env zsh

setopt APPEND_HISTORY
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt NO_HIST_ALLOW_CLOBBER
setopt NO_HIST_BEEP
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FCNTL_LOCK
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_LEX_WORDS
setopt HIST_NO_FUNCTIONS
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_BY_COPY
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt NO_INC_APPEND_HISTORY
setopt NO_INC_APPEND_HISTORY_TIME
setopt SHARE_HISTORY

export HISTFILE="$XDG_STATE_HOME"/zsh/history
export HISTSIZE=100000
export SAVEHIST=100000
