#!/usr/bin/env zsh

case "$1" in
    credentials)
        case "$2" in
            profile-creds)
                local profile="$3"

                local -a profiles
                profiles=("${(@f)$(command aws configure list-profiles)}")

                if (( ! $profiles[(Ie)$profile] )); then
                    return 1
                fi

                local source_profile
                source_profile="$(aws configure --profile="$profile" get source_profile)"

                local role_arn
                role_arn="$(aws configure --profile="$profile" get role_arn)"

                local role_session_name
                role_session_name="$(aws configure --profile="$profile" get role_session_name)"

				IFS=$'\t' read -r aws_access_key_id aws_secret_access_key aws_session_token aws_session_expiration < <(
					command aws sts assume-role \
                        --profile="$source_profile" \
						--region="${AWS_REGION:-us-east-1}" \
						--duration=3600 \
                        --role-arn="$role_arn" \
                        --role-session-name="$role_session_name" \
						--query='Credentials.[AccessKeyId, SecretAccessKey, SessionToken, Expiration]' \
						--output=text
				)

                printf 'AWS_ACCESS_KEY_ID=%q\n' "$aws_access_key_id"
                printf 'AWS_SECRET_ACCESS_KEY=%q\n' "$aws_secret_access_key"
                printf 'AWS_SESSION_TOKEN=%q\n' "$aws_session_token"
                printf 'AWS_SESSION_EXPIRATION=%q\n' "$aws_session_expiration"
                ;;

            *)
                return 1
                ;;
        esac
        ;;

    *)
        command aws "$@"
        ;;
esac
