#!/usr/bin/env zsh

is_installed emacs || return

local socket_name
if is_installed launchctl; then
	socket_name="$XDG_RUNTIME_DIR"/emacs/launchd-user.plist
elif is_installed systemctl; then
	socket_name='systemd-user.service'
fi

local -a opts=(
	"--socket-name=$socket_name"
)

command emacsclient --socket-name="$socket_name" "$@"
