#!/usr/bin/env zsh

local op_config_file="${XDG_CONFIG_HOME}"/op/config
local op_auth_session_cache="${XDG_STATE_HOME}"/op/session

if [ ! -d "$op_auth_session_cache" ]; then
    mkdir -p "$op_auth_session_cache"
    echo "# OP Auth Env Load" >> "$op_auth_session_cache"/env.load
    echo "# OP Auth Env Unload" >> "$op_auth_session_cache"/env.unload
fi

source "$op_auth_session_cache"/env.load

local subcommand="$1"
case "$subcommand" in
    'signin')
        local op_account="$2"
        if [ -z "$op_account" ]; then
            op_account="$(jq -r '.latest_signin' <"$op_config_file")"
        fi

        local -r token="$(
        	command op signin --account="$op_account" --raw --cache --session="${(P)${:-OP_SESSION_$op_account}:-no-token}"
        )"

        sed -n -i '/^export '"$op_env_value"'=/!p;$aexport '"$op_env_value"'='"'$token'" "$op_auth_session_cache"/env.load

        grep --quiet "unset OP_SESSION_$op_account" "$op_auth_session_cache"/env.unload ||
            echo "unset OP_SESSION_$op_account" >> "$op_auth_session_cache"/env.unload
        ;;

    'auth')
        local account="$2"
        case "$account" in
            aptible)
                local op_auth_item_name="${OP_AUTH_ITEM_NAME_APTIBLE:-Aptible}"

                local -r username="$(command op item get "$op_auth_item_name" --fields username)"
                local -r password="$(command op item get "$op_auth_item_name" --fields password)"
                local -r otp_token="$(command op item get "$op_auth_item_name" --field type=otp --format json | jq -r '.totp')"

                aptible login --email="$username" --password="$password" --otp-token="$otp_token" --lifetime=24h
                ;;

            aws)
                local op_auth_item_name="${OP_AUTH_ITEM_NAME_AWS:-Amazon Web Service}"

	            local -r username="$(command op item get "$op_auth_item_name" --fields username)"
	            local -r mfa_token="$(command op item get "$op_auth_item_name" --field type=otp --format json | jq -r '.totp')"
                local -r region="${3:-us-east-1}"

                aws credentials generate-mfa-session \
                    "$mfa_token" \
                    'session' \
                    'default' \
                    "arn:aws:iam::$OP_AUTH_ITEM_NAME_AWS_ACCOUNT_ID:mfa/$username" \
                    "$region"
                ;;
        esac
        ;;

    *)
        command op "$@"
        ;;
esac

source "$op_auth_session_cache"/env.unload
