#!/usr/bin/env zsh

local op_config_file="${XDG_CONFIG_HOME}"/op/config
local op_auth_session_cache="${XDG_STATE_HOME}"/op/session

if [ ! -s "$op_auth_session_cache" ]; then
	echo "# OP Session Cache" >"$op_auth_session_cache"
fi

local -a op_accounts=(
	$(jq -r  <"$op_config_file" '.accounts[]|.shorthand,.accountUUID')
)

local latest_signin="$(jq -r <"$op_config_file" '.latest_signin')"

local op_account
if (( $op_accounts[(I)$1] )); then
	op_account="$1"
	shift
else
	op_account="$latest_signin"
fi

local token="$(awk -F= "/$op_account/"'{print $2}' $op_auth_session_cache)"

local -a op_flags=("--account=${op_account}" '--cache' "--session=${token}")

local subcommand="$1"
case "$subcommand" in
	'signin')
		local new_token="$(command op signin $op_flags --raw)"

		sed -n -i '/'"$op_account"'=/!p;$a'"$op_account"'='"$new_token" "$op_auth_session_cache"

		token="$new_token"
		;;

	'auth')
		op "$op_account" signin

		local account="$2"
		case "$account" in
			aptible)
				local op_auth_item_name="${OP_AUTH_ITEM_NAME_APTIBLE:-Aptible}"

				local item_json="$(op --format=json item get "$op_auth_item_name")"

				local -r username="$(echo "$item_json" | jq -r '.fields[]|select(.id == "username").value')"
				local -r password="$(echo "$item_json" | jq -r '.fields[]|select(.id == "password").value')"
				local -r otp_token="$(echo "$item_json" | jq -r '.fields[]|select(.type == "OTP").totp')"

				aptible login --email="$username" --password="$password" --otp-token="$otp_token" --lifetime=24h
				;;

			aws)
				local op_auth_item_name="${OP_AUTH_ITEM_NAME_AWS:-Amazon Web Service}"

				local item_json="$(op --format=json item get "$op_auth_item_name")"

				local -r username="$(echo "$item_json" | jq -r '.fields[]|select(.id == "username").value')"
				local -r otp_token="$(echo "$item_json" | jq -r '.fields[]|select(.type == "OTP").totp')"
				local -r region="${3:-us-east-1}"

				aws credentials generate-mfa-session \
					"$otp_token" \
					'session' \
					'default' \
					"arn:aws:iam::$OP_AUTH_ITEM_NAME_AWS_ACCOUNT_ID:mfa/$username" \
					"$region"
				;;
		esac
		;;

	*)
		command op $op_flags "$@"
		;;
esac
