#!/usr/bin/env zsh

cat <<EOF >"$XDG_CONFIG_HOME/emacs/config/00_generated-env.el"
(mapc
 (lambda (pair)
   (let ((name (car pair))
		 (value (cdr pair)))
	 (setenv name value)
	 (when (string-equal name "PATH")
       (setq
		exec-path (append (parse-colon-path value) (list exec-directory)))
	   (setq-default
		eshell-path-env value))))
 '(("AWS_CONFIG_FILE" . "$AWS_CONFIG_FILE")
   ("AWS_SHARED_CREDENTIALS_FILE" . "$AWS_SHARED_CREDENTIALS_FILE")
   ("BOUNDARY_ADDR" . "$BOUNDARY_ADDR")
   ("BUILDKIT_PROGRESS" . "$BUILDKIT_PROGRESS")
   ("BUNDLE_USER_CACHE" . "$BUNDLE_USER_CACHE")
   ("BUNDLE_USER_CONFIG" . "$BUNDLE_USER_CONFIG")
   ("BUNDLE_USER_PLUGIN" . "$BUNDLE_USER_PLUGIN")
   ("CARGO_HOME" . "$CARGO_HOME")
   ("CPPFLAGS" . "$CPPFLAGS")
   ("DOCKER_BUILDKIT" . "$DOCKER_BUILDKIT")
   ("DOCKER_CONFIG" . "$DOCKER_CONFIG")
   ("GEM_HOME" . "$GEM_HOME")
   ("GEM_SPEC_CACHE" . "$GEM_SPEC_CACHE")
   ("GNUPGHOME" . "$GNUPGHOME")
   ("GOPATH" . "$GOPATH")
   ("GOROOT" . "$GOROOT")
   ("GRADLE_USER_HOME" . "$GRADLE_USER_HOME")
   ("GROOVY_HOME" . "$GROOVY_HOME")
   ("HOME" . "$HOME")
   ("IPYTHONDIR" . "$IPYTHONDIR")
   ("JAVA_HOME" . "$JAVA_HOME")
   ("LANG" . "$LANG")
   ("LANGUAGE" . "$LANGUAGE")
   ("LC_ALL" . "$LC_ALL")
   ("LDFLAGS" . "$LDFLAGS")
   ("MANPATH" . "$MANPATH")
   ("NODE_REPL_HISTORY" . "$NODE_REPL_HISTORY")
   ("NVM_DIR" . "$NVM_DIR")
   ("NVM_SYMLINK_CURRENT" . "$NVM_SYMLINK_CURRENT")
   ("OSTYPE" . "$OSTYPE")
   ("PARALLEL_HOME" . "$PARALLEL_HOME")
   ("PATH" . "$PATH")
   ("PIPX_BIN_DIR" . "$PIPX_BIN_DIR")
   ("PIPX_HOME" . "$PIPX_HOME")
   ("PKG_CONFIG_PATH" . "$PKG_CONFIG_PATH")
   ("POETRY_CACHE_DIR" . "$POETRY_CACHE_DIR")
   ("POETRY_HOME" . "$POETRY_HOME")
   ("POETRY_VIRTUALENVS_PATH" . "$POETRY_VIRTUALENVS_PATH")
   ("PSQL_HISTORY" . "$PSQL_HISTORY")
   ("PYENV_ROOT" . "$PYENV_ROOT")
   ("PYENV_SHELL" . "$PYENV_SHELL")
   ("PYLINTHOME" . "$PYLINTHOME")
   ("PYTHONPATH" . "$PYTHONPATH")
   ("PYTHONPYCACHEPREFIX" . "$PYTHONPYCACHEPREFIX")
   ("PYTHONSTARTUP" . "$PYTHONSTARTUP")
   ("PYTHONUTF8" . "$PYTHONUTF8")
   ("RBENV_ROOT" . "$RBENV_ROOT")
   ("RUSTUP_HOME" . "$RUSTUP_HOME")
   ("RUST_SRC_PATH" . "$(rustc --print sysroot)")
   ("SDKMAN_DIR" . "$SDKMAN_DIR")
   ("SHELL" . "$SHELL")
   ("SOLARGRAPH_CACHE" . "$SOLARGRAPH_CACHE")
   ("SPARKCTL_HOME" . "$SPARKCTL_HOME")
   ("SPARK_SETUP_HOME" . "$SPARK_SETUP_HOME")
   ("TERM" . "$TERM")
   ("TERRAFORM_REPO" . "$TERRAFORM_REPO")
   ("TF_CLI_CONFIG_FILE" . "$TF_CLI_CONFIG_FILE")
   ("TF_PLUGIN_CACHE_DIR" . "$TF_PLUGIN_CACHE_DIR")
   ("TF_VAR_formal_client_id" . "$TF_VAR_formal_client_id")
   ("TF_VAR_formal_secret_key" . "$TF_VAR_formal_secret_key")
   ("TMPDIR" . "$TMPDIR")
   ("TRIALSPARK_REPO" . "$TRIALSPARK_REPO")
   ("TZ" . "$TZ")
   ("VAULT_ADDR" . "$VAULT_ADDR")
   ("VIRTUALENVWRAPPER_PYTHON" . "$VIRTUALENVWRAPPER_PYTHON")
   ("WORKON_HOME" . "$WORKON_HOME")
   ("XDG_BIN_DIR" . "$XDG_BIN_DIR")
   ("XDG_CACHE_HOME" . "$XDG_CACHE_HOME")
   ("XDG_CONFIG_HOME" . "$XDG_CONFIG_HOME")
   ("XDG_DATA_HOME" . "$XDG_DATA_HOME")
   ("XDG_DESKTOP_DIR" . "$XDG_DESKTOP_DIR")
   ("XDG_DOCUMENTS_DIR" . "$XDG_DOCUMENTS_DIR")
   ("XDG_DOWNLOAD_DIR" . "$XDG_DOWNLOAD_DIR")
   ("XDG_MUSIC_DIR" . "$XDG_MUSIC_DIR")
   ("XDG_PICTURES_DIR" . "$XDG_PICTURES_DIR")
   ("XDG_PROJECTS_DIR" . "$XDG_PROJECTS_DIR")
   ("XDG_RUNTIME_DIR" . "$XDG_RUNTIME_DIR")
   ("XDG_STATE_HOME" . "$XDG_STATE_HOME")
   ("XDG_VIDEOS_DIR" . "$XDG_VIDEOS_DIR")
   ("XPC_FLAGS" . "$XPC_FLAGS")
   ("XPC_SERVICE_NAME" . "$XPC_SERVICE_NAME")
   ("npm_config_cache" . "$npm_config_cache")
   ("npm_config_init_module" . "$npm_config_init_module")
   ("npm_config_prefix" . "$npm_config_prefix")
   ("npm_config_tmp" . "$npm_config_tmp")
   ("npm_config_userconfig" . "$npm_config_userconfig")))
EOF
