#!/usr/bin/env zsh

setopt bad_pattern
setopt bare_glob_qual
setopt brace_ccl
setopt case_glob
setopt case_match
setopt NO_csh_null_glob
setopt equals
setopt extended_glob
setopt NO_force_float
setopt glob
setopt NO_glob_assign
setopt NO_glob_dots
setopt glob_star_short
setopt NO_glob_subst
setopt hist_subst_pattern
setopt NO_ignore_braces
setopt NO_ignore_close_braces
setopt ksh_glob
setopt magic_equal_subst
setopt mark_dirs
setopt multibyte
setopt nomatch
setopt NO_null_glob
setopt numeric_glob_sort
setopt rc_expand_param
setopt NO_rematch_pcre
setopt NO_sh_glob
setopt unset
setopt NO_warn_create_global
